#!/usr/bin/env bash
# Point this checkout at the PostgreSQL cluster running inside WSL2.
#
# Why this exists: WSL2's localhost forwarding is not available on every Windows
# host (it is off in mirrored-networking setups and can be disabled outright), so
# `127.0.0.1:5432` does not always reach a service inside the distro. The distro's
# address does work — but it is assigned per boot, so it cannot be committed.
#
# This script discovers the current address, makes sure the cluster is running,
# and writes `apps/api/.env` (gitignored). Re-run it after `wsl --shutdown` or a
# reboot.
#
#     bash infra/wsl-db-env.sh
#
# On a host where localhost forwarding *does* work, the plain connection string
# from docker-compose.yml is preferable; delete the generated .env and use it.

set -euo pipefail

DISTRO="${MRIP_WSL_DISTRO:-Ubuntu}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/apps/api/.env"

echo "==> Making sure the cluster is running in ${DISTRO}"
# Idempotent: pg_ctlcluster exits non-zero if it is already up, which is fine.
wsl.exe -d "${DISTRO}" -u root -- pg_ctlcluster 17 main start 2>/dev/null || true

# Keep the distro alive. WSL2 shuts an idle distro down a few seconds after the
# last command exits, and it takes the database with it — which looks exactly
# like a network problem: `Test-NetConnection` succeeds (the host route is still
# there) while every connection attempt times out. One long-lived process is
# enough to hold the VM up.
if ! wsl.exe -d "${DISTRO}" -u root -- pgrep -f "mrip-keepalive" >/dev/null 2>&1; then
  echo "==> Starting the keep-alive (one 24h sleep, so the VM does not idle out)"
  # Detached from this shell so the script can return.
  (wsl.exe -d "${DISTRO}" -u root -- bash -c "exec -a mrip-keepalive sleep 86400" &) \
    >/dev/null 2>&1
  sleep 3
fi

address="$(wsl.exe -d "${DISTRO}" -- hostname -I | tr -d '\0\r' | awk '{print $1}')"
if [ -z "${address}" ]; then
  echo "Could not read the distro's address. Is ${DISTRO} installed and started?" >&2
  exit 1
fi

echo "==> ${DISTRO} is at ${address}"
cat > "${ENV_FILE}" <<ENV
# Generated by infra/wsl-db-env.sh — do not commit (gitignored).
#
# The database runs in WSL2, whose address is assigned per boot. Re-run
# infra/wsl-db-env.sh after 'wsl --shutdown' or a reboot to refresh this.
MRIP_DATABASE_URL=postgresql+psycopg://mrip:mrip_dev_only@${address}:5432/mrip
MRIP_TEST_DATABASE_URL=postgresql+psycopg://mrip:mrip_dev_only@${address}:5432/mrip_test
ENV

echo "==> Wrote ${ENV_FILE}"
sed -n '4,6p' "${ENV_FILE}"
cat <<'NEXT'

The suite picks this up on its own: tests/conftest.py reads
MRIP_TEST_DATABASE_URL from the environment first and from apps/api/.env
second. Run pytest from apps/api.

If connections start timing out later, the distro has idled out (its address
changes on the next start, too). Re-run this script.
NEXT
