"""baseline schema

Revision ID: 0001
Revises:
Created: 2026-09-23 17:26:55.243325
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("job_id", sa.Text(), nullable=False),
        sa.Column(
            "queue", sa.Text(), server_default=sa.text("'default'"), nullable=False
        ),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "claimed",
                "succeeded",
                "failed",
                "dead",
                name="job_state",
                native_enum=False,
            ),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "max_attempts", sa.Integer(), server_default=sa.text("3"), nullable=False
        ),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_by", sa.Text(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state <> 'claimed' OR (claimed_by IS NOT NULL AND lease_expires_at IS NOT NULL)",
            name=op.f("ck_jobs_claimed_jobs_have_a_lease"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_jobs_attempts_nonnegative")),
        sa.CheckConstraint(
            "max_attempts >= 1", name=op.f("ck_jobs_max_attempts_positive")
        ),
        sa.PrimaryKeyConstraint("job_id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_jobs_idempotency_key")),
    )
    op.create_index(
        "ix_jobs_claimable",
        "jobs",
        ["queue", sa.literal_column("priority DESC"), "available_at"],
        unique=False,
        postgresql_where=sa.text("state = 'pending'"),
    )
    op.create_index(
        "ix_jobs_expired_leases",
        "jobs",
        ["lease_expires_at"],
        unique=False,
        postgresql_where=sa.text("state = 'claimed'"),
    )
    op.create_index("ix_jobs_state", "jobs", ["state"], unique=False)
    op.create_table(
        "users",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column(
            "auth_source",
            sa.Enum("local", "oidc", "ldap", name="auth_source", native_enum=False),
            server_default=sa.text("'local'"),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum(
                "viewer",
                "officer",
                "reviewer",
                "approver",
                "admin",
                name="role",
                native_enum=False,
            ),
            server_default=sa.text("'viewer'"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "auth_source <> 'local' OR password_hash IS NOT NULL",
            name=op.f("ck_users_local_accounts_have_a_hash"),
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "audit_log",
        sa.Column("audit_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Text(), nullable=True),
        sa.Column("actor_username", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("subject_type", sa.Text(), nullable=True),
        sa.Column("subject_id", sa.Text(), nullable=True),
        sa.Column("entity_scope", sa.Text(), nullable=True),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column("source_ip", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.user_id"],
            name=op.f("fk_audit_log_actor_user_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("audit_id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "ix_audit_log_actor", "audit_log", ["actor_user_id", "occurred_at"], unique=False
    )
    op.create_index(
        "ix_audit_log_occurred_at", "audit_log", ["occurred_at"], unique=False
    )
    op.create_index(
        "ix_audit_log_subject", "audit_log", ["subject_type", "subject_id"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("document_id", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("blob_key", sa.Text(), nullable=True),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column(
            "doc_class",
            sa.Enum(
                "text_pdf",
                "scanned_pdf",
                "mixed_pdf",
                "spreadsheet",
                "docx",
                "image",
                "unknown",
                name="document_class",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("supersedes", sa.Text(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("publisher_entity_id", sa.Text(), nullable=True),
        sa.Column("fiscal_year", sa.Text(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "is_synthetic", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "received",
                "classified",
                "digitized",
                "extracted",
                "normalized",
                "validated",
                "indexed",
                "ready",
                "failed",
                "quarantined",
                name="document_state",
                native_enum=False,
            ),
            server_default=sa.text("'received'"),
            nullable=False,
        ),
        sa.Column(
            "sensitivity",
            sa.Enum(
                "public", "internal", "restricted", name="sensitivity", native_enum=False
            ),
            server_default=sa.text("'internal'"),
            nullable=False,
        ),
        sa.Column("failed_stage", sa.Text(), nullable=True),
        sa.Column("failed_reason", sa.Text(), nullable=True),
        sa.Column(
            "stage_progress",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("owner_entity_id", sa.Text(), nullable=True),
        sa.Column("uploaded_by", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state <> 'failed' OR failed_stage IS NOT NULL",
            name=op.f("ck_documents_failure_names_its_stage"),
        ),
        sa.CheckConstraint(
            "page_count IS NULL OR page_count >= 0",
            name=op.f("ck_documents_page_count_nonnegative"),
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_documents_size_nonnegative")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_documents_version_positive")),
        sa.ForeignKeyConstraint(
            ["supersedes"],
            ["documents.document_id"],
            name=op.f("fk_documents_supersedes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.user_id"],
            name=op.f("fk_documents_uploaded_by"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("document_id", name=op.f("pk_documents")),
        sa.UniqueConstraint("document_id", "version", name="document_version"),
    )
    op.create_index(
        "ix_documents_fiscal_year", "documents", ["fiscal_year"], unique=False
    )
    op.create_index(
        "ix_documents_owner_entity", "documents", ["owner_entity_id"], unique=False
    )
    op.create_index("ix_documents_state", "documents", ["state"], unique=False)
    # Unique on lower(content_hash): SHA-256 digests are printed in both cases by
    # different tools, and a plain unique constraint would accept both spellings
    # of one file, double-counting every fact in it.
    op.execute(
        "CREATE UNIQUE INDEX uq_documents_content_hash_lower "
        "ON documents (lower(content_hash))"
    )
    op.create_table(
        "user_scopes",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("granted_by", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.user_id"],
            name=op.f("fk_user_scopes_granted_by"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_user_scopes_user_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "entity_id", name=op.f("pk_user_scopes")),
    )
    op.create_table(
        "evidence",
        sa.Column("evidence_id", sa.Text(), nullable=False),
        sa.Column("document_id", sa.Text(), nullable=False),
        sa.Column(
            "document_version", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("table_id", sa.Text(), nullable=True),
        sa.Column("cell_ref", sa.Text(), nullable=True),
        sa.Column("row_idx", sa.Integer(), nullable=True),
        sa.Column("col_idx", sa.Integer(), nullable=True),
        sa.Column("bbox_x0", sa.Double(), nullable=True),
        sa.Column("bbox_y0", sa.Double(), nullable=True),
        sa.Column("bbox_x1", sa.Double(), nullable=True),
        sa.Column("bbox_y1", sa.Double(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("ocr_confidence", sa.Double(), nullable=True),
        sa.Column(
            "extraction_method",
            sa.Enum(
                "pdf_text_layer",
                "ocr",
                "table_lattice",
                "table_stream",
                "spreadsheet_cell",
                "vlm",
                "manual",
                name="extraction_method",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ocr_confidence IS NULL OR (ocr_confidence >= 0 AND ocr_confidence <= 1)",
            name=op.f("ck_evidence_ocr_confidence_is_probability"),
        ),
        sa.CheckConstraint(
            "page IS NULL OR page >= 1", name=op.f("ck_evidence_page_positive")
        ),
        sa.ForeignKeyConstraint(
            ["document_id", "document_version"],
            ["documents.document_id", "documents.version"],
            name="document_version",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("evidence_id", name=op.f("pk_evidence")),
    )
    op.create_index(
        "ix_evidence_doc_page", "evidence", ["document_id", "page"], unique=False
    )
    op.create_index(
        "ix_evidence_table", "evidence", ["document_id", "table_id"], unique=False
    )
    op.create_table(
        "facts",
        sa.Column("fact_id", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=False),
        sa.Column("mine_or_block", sa.Text(), nullable=True),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("value", sa.Double(), nullable=False),
        sa.Column("unit", sa.Text(), nullable=False),
        sa.Column("dimension", sa.Text(), nullable=False),
        sa.Column("raw_value", sa.Double(), nullable=False),
        sa.Column("raw_unit", sa.Text(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("period_label", sa.Text(), nullable=False),
        sa.Column("fiscal_year", sa.Text(), nullable=True),
        sa.Column("document_id", sa.Text(), nullable=False),
        sa.Column(
            "document_version", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("table_id", sa.Text(), nullable=True),
        sa.Column("cell_ref", sa.Text(), nullable=True),
        sa.Column("bbox_x0", sa.Double(), nullable=True),
        sa.Column("bbox_y0", sa.Double(), nullable=True),
        sa.Column("bbox_x1", sa.Double(), nullable=True),
        sa.Column("bbox_y1", sa.Double(), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column(
            "extraction_method",
            sa.Enum(
                "pdf_text_layer",
                "ocr",
                "table_lattice",
                "table_stream",
                "spreadsheet_cell",
                "vlm",
                "manual",
                name="extraction_method",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("conf_ocr", sa.Double(), nullable=True),
        sa.Column("conf_parse", sa.Double(), nullable=True),
        sa.Column("conf_answer", sa.Double(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "extracted",
                "validated",
                "needs_review",
                "conflicted",
                "superseded",
                "rejected",
                name="fact_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "review_state",
            sa.Enum(
                "unreviewed",
                "approved",
                "corrected",
                "rejected",
                name="review_state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "unit_ambiguous",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "extracted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(conf_ocr    IS NULL OR (conf_ocr    BETWEEN 0 AND 1)) AND (conf_parse  IS NULL OR (conf_parse  BETWEEN 0 AND 1)) AND (conf_answer IS NULL OR (conf_answer BETWEEN 0 AND 1))",
            name=op.f("ck_facts_confidences_are_probabilities"),
        ),
        sa.CheckConstraint(
            "period_end >= period_start", name=op.f("ck_facts_period_ordered")
        ),
        sa.ForeignKeyConstraint(
            ["document_id", "document_version"],
            ["documents.document_id", "documents.version"],
            name="document_version",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("fact_id", name=op.f("pk_facts")),
    )
    op.create_index(
        "ix_facts_conflict_key",
        "facts",
        ["entity_id", "metric", "unit", "period_label"],
        unique=False,
    )
    op.create_index("ix_facts_document", "facts", ["document_id"], unique=False)
    op.create_index(
        "ix_facts_lookup", "facts", ["entity_id", "metric", "fiscal_year"], unique=False
    )
    op.create_index("ix_facts_status", "facts", ["status"], unique=False)
    op.create_table(
        "conflicts",
        sa.Column("conflict_id", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=False),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("unit", sa.Text(), nullable=False),
        sa.Column("period_label", sa.Text(), nullable=False),
        sa.Column("value_low", sa.Double(), nullable=False),
        sa.Column("value_high", sa.Double(), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_fact_id", sa.Text(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("resolved_by", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(resolved_fact_id IS NULL) = (resolved_at IS NULL)",
            name=op.f("ck_conflicts_resolution_is_all_or_nothing"),
        ),
        sa.CheckConstraint(
            "value_high >= value_low", name=op.f("ck_conflicts_values_ordered")
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.user_id"],
            name=op.f("fk_conflicts_resolved_by"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_fact_id"],
            ["facts.fact_id"],
            name=op.f("fk_conflicts_resolved_fact_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("conflict_id", name=op.f("pk_conflicts")),
    )
    op.create_index(
        "ix_conflicts_open_key",
        "conflicts",
        ["entity_id", "metric", "unit", "period_label"],
        unique=True,
        postgresql_where=sa.text("resolved_fact_id IS NULL"),
    )
    op.create_table(
        "conflict_facts",
        sa.Column("conflict_id", sa.Text(), nullable=False),
        sa.Column("fact_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conflict_id"],
            ["conflicts.conflict_id"],
            name=op.f("fk_conflict_facts_conflict_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["fact_id"],
            ["facts.fact_id"],
            name=op.f("fk_conflict_facts_fact_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("conflict_id", "fact_id", name=op.f("pk_conflict_facts")),
    )
    op.create_index("ix_conflict_facts_fact", "conflict_facts", ["fact_id"], unique=False)
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Audit-log immutability.
    #
    # A trigger rather than `REVOKE UPDATE, DELETE`, because a table's owner keeps
    # its privileges regardless of what is revoked — and in most deployments the
    # application account *is* the owner. The trigger binds everyone, including the
    # owner and including a superuser, so the append-only claim in
    # docs/ARCHITECTURE.md §9 is enforced by the database rather than by the good
    # behaviour of whoever writes the next repository method.
    #
    # Removing it is possible, but only by DDL — which is a visible, reviewable act,
    # unlike a stray UPDATE.
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION mrip_audit_log_is_append_only()
        RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION
                'audit_log is append-only: % is not permitted', TG_OP
                USING ERRCODE = 'restrict_violation',
                      HINT = 'Correct the record with a new compensating entry.';
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_no_update_or_delete
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION mrip_audit_log_is_append_only();
        """
    )
    # TRUNCATE bypasses row-level triggers, so it needs its own statement-level one.
    op.execute(
        """
        CREATE TRIGGER audit_log_no_truncate
        BEFORE TRUNCATE ON audit_log
        FOR EACH STATEMENT EXECUTE FUNCTION mrip_audit_log_is_append_only();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_truncate ON audit_log")
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_update_or_delete ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS mrip_audit_log_is_append_only()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_conflict_facts_fact", table_name="conflict_facts")
    op.drop_table("conflict_facts")
    op.drop_index(
        "ix_conflicts_open_key",
        table_name="conflicts",
        postgresql_where=sa.text("resolved_fact_id IS NULL"),
    )
    op.drop_table("conflicts")
    op.drop_index("ix_facts_status", table_name="facts")
    op.drop_index("ix_facts_lookup", table_name="facts")
    op.drop_index("ix_facts_document", table_name="facts")
    op.drop_index("ix_facts_conflict_key", table_name="facts")
    op.drop_table("facts")
    op.drop_index("ix_evidence_table", table_name="evidence")
    op.drop_index("ix_evidence_doc_page", table_name="evidence")
    op.drop_table("evidence")
    op.drop_table("user_scopes")
    op.execute("DROP INDEX IF EXISTS uq_documents_content_hash_lower")
    op.drop_index("ix_documents_state", table_name="documents")
    op.drop_index("ix_documents_owner_entity", table_name="documents")
    op.drop_index("ix_documents_fiscal_year", table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_audit_log_subject", table_name="audit_log")
    op.drop_index("ix_audit_log_occurred_at", table_name="audit_log")
    op.drop_index("ix_audit_log_actor", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("users")
    op.drop_index("ix_jobs_state", table_name="jobs")
    op.drop_index(
        "ix_jobs_expired_leases",
        table_name="jobs",
        postgresql_where=sa.text("state = 'claimed'"),
    )
    op.drop_index(
        "ix_jobs_claimable",
        table_name="jobs",
        postgresql_where=sa.text("state = 'pending'"),
    )
    op.drop_table("jobs")
    # ### end Alembic commands ###
